"""
    Contains definitions that are shared between different generators
"""

DEFAULT_WIDTH = 16  # default value for the width
DEFAULT_TILE_SIZE = 256  # default value for the tiling
DEFAULT_2D_CTILE_WIDTH = 8  # default width (x or y) in case of 2D computational tiling

### Base names for kernels, channels,...
HELPER_READ_VECTOR_X_BASE_NAME = "kernel_read_vector_x_"
HELPER_READ_VECTOR_Y_BASE_NAME = "kernel_read_vector_y_"
HELPER_READ_VECTOR_X_TRANS_BASE_NAME = "kernel_read_vector_x_trans_"
HELPER_READ_VECTOR_Y_TRANS_BASE_NAME = "kernel_read_vector_y_trans_"
HELPER_READ_VECTOR_X_TRSV_BASE_NAME = "kernel_read_write_vector_x_trsv_"
HELPER_READ_MATRIX_A_BASE_NAME = "kernel_read_matrix_A_"
HELPER_READ_MATRIX_A2_BASE_NAME = "kernel_read_matrix_A2_"
HELPER_READ_MATRIX_B_BASE_NAME = "kernel_read_matrix_B_"
HELPER_READ_MATRIX_B2_BASE_NAME = "kernel_read_matrix_B2_"
HELPER_WRITE_SCALAR_BASE_NAME = "kernel_write_scalar_"
HELPER_WRITE_VECTOR_BASE_NAME = "kernel_write_vector_"
HELPER_WRITE_VECTOR_X_Y_BASE_NAME = "kernel_write_vectors_"
HELPER_WRITE_MATRIX_BASE_NAME = "kernel_write_matrix_"

CHANNEL_IN_VECTOR_X_BASE_NAME = "channel_in_vector_x_"
CHANNEL_IN_VECTOR_Y_BASE_NAME = "channel_in_vector_y_"
CHANNEL_IN_VECTOR_X_TRANS_BASE_NAME = "channel_in_vector_x_trans_"
CHANNEL_IN_VECTOR_Y_TRANS_BASE_NAME = "channel_in_vector_y_trans_"
CHANNEL_IN_VECTOR_X_TRSV_BASE_NAME = "channel_in_vector_x_trsv_"
CHANNEL_IN_MATRIX_A_BASE_NAME = "channel_in_matrix_A_"
CHANNEL_IN_MATRIX_A2_BASE_NAME = "channel_in_matrix_A2_"
CHANNEL_IN_MATRIX_B_BASE_NAME = "channel_in_matrix_B_"
CHANNEL_IN_MATRIX_B2_BASE_NAME = "channel_in_matrix_B2_"
CHANNEL_OUT_SCALAR_BASE_NAME = "channel_out_scalar_"
CHANNEL_OUT_VECTOR_BASE_NAME = "channel_out_vector_"
CHANNEL_OUT_VECTOR_X_BASE_NAME = "channel_out_vector_x_"
CHANNEL_OUT_VECTOR_Y_BASE_NAME = "channel_out_vector_y_"
CHANNEL_OUT_MATRIX_BASE_NAME = "channel_out_matrix_"

##### Template names for Helpers
TEMPLATE_READ_VECTOR_X = "read_vector_x.cl"
TEMPLATE_READ_VECTOR_Y = "read_vector_y.cl"
TEMPLATE_WRITE_SCALAR = "write_scalar.cl"
TEMPLATE_WRITE_VECTOR = "write_vector.cl"
TEMPLATE_WRITE_VECTOR_X_Y = "write_two_vectors.cl"
TEMPLATE_READ_VECTOR_X_TRANS_LOWER = "read_vector_x_incremental_low.cl"
TEMPLATE_READ_VECTOR_X_TRANS_UPPER = "read_vector_x_incremental_upper.cl"
TEMPLATE_READ_VECTOR_Y_TRANS_LOWER = "read_vector_y_incremental_low.cl"
TEMPLATE_READ_VECTOR_Y_TRANS_UPPER = "read_vector_y_incremental_upper.cl"
TEMPLATE_READ_WRITE_VECTOR_X_TRSV_LOWER = "read_write_vector_x_trsv_low.cl"
TEMPLATE_READ_WRITE_VECTOR_X_TRSV_UPPER = "read_write_vector_x_trsv_upper.cl"

TEMPLATE_READ_MATRIX_ROWSTREAMED_TILE_ROW = "read_matrix_rowstreamed_tile_row.cl"
TEMPLATE_READ_MATRIX_ROWSTREAMED_TILE_COL = "read_matrix_rowstreamed_tile_col.cl"
TEMPLATE_READ_MATRIX_ROWSTREAMED_TILE_ROW_4_MODULES = "read_matrix_rowstreamed_tile_row_4_modules.cl"
TEMPLATE_READ_LOWER_MATRIX_ROWSTREAMED_TILE_ROW = "read_lower_matrix_rowstreamed_tile_row.cl"
TEMPLATE_READ_UPPER_MATRIX_ROWSTREAMED_TILE_ROW = "read_upper_matrix_rowstreamed_tile_row.cl"
TEMPLATE_READ_UPPER_MATRIX_ROWSTREAMED_TILE_COL = "read_upper_matrix_rowstreamed_tile_col.cl"
TEMPLATE_READ_REVERSE_LOWER_MATRIX_ROWSTREAMED_TILE_COL = "read_reverse_lower_matrix_rowstreamed_tile_col.cl"
TEMPLATE_READ_REVERSE_UPPER_MATRIX_ROWSTREAMED_TILE_ROW = "read_reverse_upper_matrix_rowstreamed_tile_row.cl"
TEMPLATE_WRITE_MATRIX_ROWSTREAMED_TILE_ROW = "write_matrix_rowstreamed_tile_row.cl"
TEMPLATE_WRITE_LOWER_MATRIX_ROWSTREAMED_TILE_ROW = "write_lower_matrix_rowstreamed_tile_row.cl"
TEMPLATE_WRITE_UPPER_MATRIX_ROWSTREAMED_TILE_ROW = "write_upper_matrix_rowstreamed_tile_row.cl"
TEMPLATE_GENERATE_DUMMY_VECTOR = "generate_dummy_vector.cl"
TEMPLATE_GENERATE_DUMMY_MATRIX = "generate_dummy_matrix.cl"
TEMPLATE_VECTOR_SINK = "vector_sink.cl"

# Matrix helpers for gemm
TEMPLATE_READ_MATRIX_A_GEMM_NOTRANS = "read_matrix_a_notrans_gemm.cl"
TEMPLATE_READ_MATRIX_A_GEMM_TRANS = "read_matrix_a_trans_gemm.cl"
TEMPLATE_READ_MATRIX_B_GEMM_TRANS = "read_matrix_b_trans_gemm.cl"
TEMPLATE_READ_MATRIX_B_GEMM_NOTRANS = "read_matrix_b_notrans_gemm.cl"
TEMPLATE_WRITE_MATRIX_GEMM = "write_matrix_gemm.cl"
TEMPLATE_READ_MATRIX_A_GEMM_NOTRANS_SYSTOLIC = "read_matrix_a_notrans_gemm_systolic.cl"
TEMPLATE_READ_MATRIX_A_GEMM_TRANS_SYSTOLIC = "read_matrix_a_trans_gemm_systolic.cl"
TEMPLATE_READ_MATRIX_B_GEMM_TRANS_SYSTOLIC = "read_matrix_b_trans_gemm_systolic.cl"
TEMPLATE_READ_MATRIX_B_GEMM_NOTRANS_SYSTOLIC = "read_matrix_b_notrans_gemm_systolic.cl"
TEMPLATE_READ_MATRIX_A_SYRK_NOTRANS = "read_matrix_a_notrans_syrk.cl"
TEMPLATE_READ_MATRIX_A_SYRK_TRANS = "read_matrix_a_trans_syrk.cl"
TEMPLATE_READ_MATRIX_A2_SYRK_NOTRANS = "read_matrix_a2_notrans_syrk.cl"
TEMPLATE_READ_MATRIX_A2_SYRK_TRANS = "read_matrix_a2_trans_syrk.cl"

TEMPLATE_WRITE_MATRIX_GEMM_SYSTOLIC = "write_matrix_gemm_systolic.cl"
TEMPLATE_WRITE_MATRIX_SYRK_LOWER = "write_lower_matrix_syrk.cl"
TEMPLATE_WRITE_MATRIX_SYRK_UPPER = "write_upper_matrix_syrk.cl"

